server:
  port: ${app.port:8080}

spring:
  output:
    ansi:
      enabled: always
  application:
    name: transaccion-cajero-automatico
  datasource:
    url: jdbc:postgresql://postgres_database:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        ddl-auto: create

    hikari:
      connection-test-query: select 1

